### ISSUE TITLE
Cache cloudbuild process → save time & resurces

### ISSUE THREAD

**Issue by seralekseenko** [assistant-ai/jess#27]
The problem:  any build step which does `go build` or `go test` download same dependencies step by step.

Possible solution: pass between builder steps early downloaded packages. 
One more: maybe there is the reason save dependencies like an `*.tar.gz` in Google Cloud Storage → it'll be faster to download dependencies. Save `*.tar.gz` after all `go build` & get and unpack before `go tidy`.

Tech details:
1. Each step that needs a cache of dependencies from previous steps or builds must be connected to a common volume with them, on which these dependencies are stored.
Q: But how to force Golang to look for dependencies in the common volume?
A: ??
Q:  If I do correctly create a shared volume with dependencies for Golang, then why does Golang still not see them and re-download all dependencies in all steps that I think already have a shared dependency cache?
A: ??

2. Cache steps for `cloudbuild.yaml` before go-builders and after:

```yaml

steps:
  # Download golang cache
  - name: 'gcr.io/cloud-builders/gsutil'
    id: pull-pkg-cache
    waitFor: [ '-' ]
    dir: '/builder/home/go/'
    script: '
      echo "ls -lah" && ls -lah &&
      gsutil -m cp gs://jess-artifacts/build_cache/go-pkg.tar.gz /tmp/go-pkg.tar.gz &&
      tar -xzf /tmp/go-pkg.tar.gz || echo "Cache archive not found!" &&
      rm -rf /root/.cache/pip &&
      echo "ls -lah /builder/home/go/" && ls -lah /builder/home/go/ || true &&
      echo "ls -lah /builder/home/go/pkg" && ls -lah /builder/home/go/pkg || true &&
      touch TROLOLO.txt
      '
    volumes:
      - name: go-pkg
        path: /builder/home/go/
        
# More steps. Like `go tidy`, `go test`, `go build` ....
    

  # Build the Windows binary for example
  - name: 'gcr.io/cloud-builders/go:1.20'
    id: build-windows
    waitFor: [ 'tests' ]
    env: [ 'GO111MODULE=on', 'CGO_ENABLED=0', 'GOOS=windows', 'GOARCH=amd64' ]
    script: 'go build -ldflags="-X main.version=$(cat VERSION)" -o jess-windows-amd64.exe -v'
    volumes:
      - name: go-pkg
        path: /builder/home/go/
  
  # Save build cache
  - name: 'gcr.io/cloud-builders/gsutil'
    id: save-pkg-cache
    waitFor: ['build-macOS', 'build-windows', 'build-linux']
    dir: '/builder/home/go/'
    script: '
      tar -czf /tmp/go-pkg.tar.gz pkg &&
      gsutil -m cp /tmp/go-pkg.tar.gz gs://jess-artifacts/build_cache/go-pkg.tar.gz
      echo "ls -lah /builder/home/go" && ls -lah /builder/home/go || true
      '
    volumes:
      - name: go-pkg
        path: /builder/home/go/
        
```
